name: Pull Request

on:
  pull_request:
  merge_group:
    branches:
      - 'main'

jobs:
  ktLint:
    name: Verify code format (KtLint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Gradlew task
        run: bash ./gradlew --no-daemon --no-parallel ktlintCheck

  androidLint:
    name: Android linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Gradlew task
        run: bash ./gradlew --no-daemon --no-parallel lintDebug